backend = "glx";

opacity-rule = [
  "60:name = 'ncmpc'",
  "70:class_g = 'kitty' && !focused",
  "80:class_g = 'kitty' && focused"
];

shadow = false;
shadow-radius = 30;
shadow-offset-x = -20;
shadow-offset-y = -20;
shadow-opacity = 0.8;
shadow-red = 0.03;
shadow-green = 0.03;
shadow-blue = 0.03;

fading = true;
fade-delta = 15;

wintypes:
{
  menu = { shadow = true; };
  notification = { shadow = true; };
  splash = { shadow = true; };
};
