abstracts = {
  sb = "%C[%M$*%C]%n ";
  sb_act_sep = "%C$*%n";
  sb_act_text = "%m$*%n";
  sb_act_msg = "%g$*%n";
  sb_background = "%0";
  sbmode = " %C+%m$*%n";
  sbnickmode = "%r$0%n";
  sbservertag = ":%g$0%n";

  channel = "%g$*%n";
  channelhilight = "%g$*%n";
  nickhost = "%M[%g$*%M]%n";
  server = "%g$*%n";

  dccownnick = "%m$*%n";
  menick = "%m$*%n";
  nick = "%m$*%n";
  ownnick = "%m$*%n";
  ownprivnick = "%m$*%n";
  pubnick = "%m$*%n";

  msgnick = "%C %n%|$1- ";
  ownmsgnick = "%y %n%|";
  ownprivmsgnick = "{ownmsgnick $*}";

  ban = "%r$*%n";
  comment = "%K[%G$*%K]%n";
  error = "%R$*%n";
  hilight = "%G$*%n";
  line_start = "%C󱗽 %n";
  mode = "{comment $*}";
  prompt = "%C$*:%n ";
  reason = "%C({comment $*}%C)%n";
  timestamp = "%M$*%n";

  errormessage = "%R %n $*";
  warningmessage = "%Y %n $*";

  action = "%C󱐋 %|%m$0%n $1";
  ownaction = "%y󱐋 %|%m$0%n $1";
  ownaction_target = "%y󱐋 %m$1 %y %m$0%n ";
  pvtaction = "{action $*}";

  ownnotice = "%y󱃝 %m$1-%n ";
  notice = "%r󱃛 %R$* %n";
  pubnotice_channel = "%K:%g$*%n";
  pvtnotice_host = "%K(%g$*%K)%n";
  servernotice = "%g$*%n ";
};
