allow_remote_control yes
enable_audio_bell no
listen_on unix:@kitty
tab_bar_style powerline
update_check_interval 0

font_family CaskaydiaCove Nerd Font
font_size 14

cursor_shape underline
cursor_blink_interval 0
cursor #6C6370
cursor_text_color #2C323C

selection_foreground #2C323C
selection_background #5C6370

foreground #C5C8C6
background #1D1F21
# black
color0 #1D1F21
color8 #3E4452
# red
color1 #AB4642
color9 #E06C75
# green
color2 #A1B56C
color10 #98C379
# yellow
color3 #DC9656
color11 #E5C07B
# blue
color4 #62A0EA
color12 #7CAFC2
# magenda
color5 #A16946
color13 #BA8BAF
# cyan
color6 #56B6C2
color14 #86C1B9
# white
color7 #5C6370
color15 #C5C8C6
