#!/bin/sh

echo fonts
fc-cache -r

echo icon caches
update-icon-caches /usr/share/icons/*
update-icon-caches /usr/local/share/icons/*

echo desktop databases
update-desktop-database /usr/share/applications
update-desktop-database /usr/local/share/applications

echo delete (doc help locale ..)
rm -r /usr/share/bug
rm -r /usr/share/doc
rm -r /usr/share/help
rm -r /usr/share/info
rm -r /usr/share/locale

echo libs
ldconfig
