#!/bin/sh

gpg --export --export-options backup --output ~/documents/etc/public.gpg
gpg --export-secret-keys --export-options backup --output ~/documents/etc/private.gpg
gpg --export-ownertrust > ~/documents/etc/trust.gpg