options iwlwifi 11n_disable=1  # 1: disable 802.11n; 8 enable antenna aggregation
options iwlwifi swcrypto=1  # enable software encryption - helps performance on some intel cards
options iwlwifi bt_coex_active=0