Section "Monitor"
  Identifier "VGA-0"
  VendorName "BenQ"
  ModelName "G2222HDL"
  HorizSync 24.0 - 83.0
  VertRefresh 50.0 - 76.0
  Option "DPMS"
EndSection

Section "Monitor"
  Identifier "LVDS-0"
  VendorName "Asus"
  ModelName "160AT06"
  Option "DPMS"
EndSection