music_directory	"~/music"
playlist_directory "~/.config/mpd"
db_file	"~/.cache/mpd/db"
log_file "~/.cache/mpd/log"
pid_file "~/.cache/mpd/pid"
state_file "~/.cache/mpd/state"
sticker_file "~/.cache/mpd/sticker"

bind_to_address "localhost"

#audio_output {
#  type "alsa"
#  name "ALSA sound card"
#  device "hw:CARD=Intel,DEV=0"  # `aplay --list-pcm
#  mixer_type "hardware"
#  mixer_device "default"
#  mixer_control "Master"  # `amixer scontrols
#  mixer_index "0"
#}

audio_output {
  type "pulse"
  name "pulse audio"
}

decoder {
  plugin "hybrid_dsd"
  enabled "no"
}

decoder {
  plugin "wildmidi"
  enabled "no"
}
