alias c="clear"
alias deb="deborphan -aD"
alias e="exit"
alias g="grep --color=auto"
alias irssi="irssi --home=~/.local/share/irssi"
alias ls="ls --color=auto"
alias l="ls -A"
alias ll="ls -lA"
alias mc="mc -x"
alias pkexec="pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY"
alias unset="set --erase"
