alias c="clear"
alias e="exit"
alias irssi="irssi --home=~/.local/share/irssi"
alias ls="ls --color=auto"
alias l="ls -A"
alias ll="ls -lA"
alias mc="mc --xterm"
alias pkexec="pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY"
alias unset="set --erase"
